---
box:
  :client_id: 6y78xghi2uc1jg6c78aardhu3mubsow9
  :client_secret: SaernPsOVgnXuSnSLxy5obxlDnLpEtI2
drop_box:
  :app_key: go7srjky5fir1iv
  :app_secret: xga51jmfr8e50ou
google_drive:
  :client_id: AIzaSyBYtDjk8__0gDKVo1NU9ZjqrCoEU9fTtCI
  :client_secret: NyPx_DYq3pqP1k9a5va2H2kf

