---
box:
  :client_id: 3slqp7u7kaqgjyzwbw1n7kjhrl5cgklh
  :client_secret: Rg0rnqPfeYEhSNQIGcXvFI8CYKAZCpC3
drop_box:
  :app_key: a9ux5k2syk8z6fp
  :app_secret: uza09ihs9uaxghc
google_drive:
  :client_id: 896165996291.apps.googleusercontent.com
  :client_secret: JcOyVnl1MUMUJt0tCVAwd4Ag

